SELECT
    p.id,
    EXTRACT(YEAR FROM AGE(p.date_of_birth))::INT AS age,
    p.gender_id, p.orientation_id, p.ethnicity_id, p.height_cm,
    p.looking_for_id, p.smoking_id, p.drinking_id, p.drugs_id,
    p.long_distance_id, p.relationship_status_id, p.has_kids_id,
    p.wants_kids_id, p.exercise_id, p.religion_id, p.star_sign_id,
    ST_Y(p.coordinates::geometry) AS lat,
    ST_X(p.coordinates::geometry) AS lon,
    p.location_country AS country,
    p.count_answers,
    p.activated,
    p.shadow_banned_at IS NOT NULL AS shadow_banned,
    'bot' = ANY(p.roles) AS is_bot,
    p.verification_level_id,
    p.hide_me_from_strangers,
    p.sign_up_time,
    p.last_online_time,
    EXISTS (SELECT 1 FROM photo WHERE photo.person_id = p.id) AS has_photo,
    p.personality::TEXT AS personality,
    p.education IS NOT NULL AS has_education,
    p.occupation IS NOT NULL AS has_occupation,
    LENGTH(p.about) AS about_len
FROM person p
