from serviceshared.duoenv.read import (
    flag_with,
    float_with,
    int_with,
    str_or_none,
    str_with,
)

MAX_RANDOM_START_DELAY = int_with('DUO_CRON_MAX_RANDOM_START_DELAY', 15)

OFFPEAK_MAX_LOAD_PCT = float_with('DUO_CRON_OFFPEAK_MAX_LOAD_PCT', 75.0)

PHOTO_CLEANER_DRY_RUN = flag_with('DUO_CRON_PHOTO_CLEANER_DRY_RUN', 'true')
PHOTO_CLEANER_POLL_SECONDS = int_with('DUO_CRON_PHOTO_CLEANER_POLL_SECONDS', 60)

AUDIO_CLEANER_DRY_RUN = flag_with('DUO_CRON_AUDIO_CLEANER_DRY_RUN', 'true')
AUDIO_CLEANER_POLL_SECONDS = int_with('DUO_CRON_AUDIO_CLEANER_POLL_SECONDS', 60)

CHECK_PHOTOS_DRY_RUN = flag_with('DUO_CRON_CHECK_PHOTOS_DRY_RUN', 'true')
CHECK_PHOTOS_POLL_SECONDS = int_with('DUO_CRON_CHECK_PHOTOS_POLL_SECONDS', 1)

# Shared by the message-notification and visitor-notification crons.
EMAIL_POLL_SECONDS = int_with('DUO_CRON_EMAIL_POLL_SECONDS', 10)

GARBAGE_RECORDS_POLL_SECONDS = \
    int_with('DUO_CRON_GARBAGE_RECORDS_POLL_SECONDS', 10)

NSFW_PHOTO_RUNNER_POLL_SECONDS = \
    int_with('DUO_CRON_NSFW_PHOTO_RUNNER_POLL_SECONDS', 1)

PROFILE_REPORTER_POLL_SECONDS = \
    int_with('DUO_CRON_PROFILE_REPORTER_POLL_SECONDS', 10 * 60)

VERIFICATION_POLL_SECONDS = int_with('DUO_CRON_VERIFICATION_POLL_SECONDS', 1)

CLUB_STATS_MAX_AGE_DAYS = int_with('DUO_CRON_CLUB_STATS_MAX_AGE_DAYS', 7)
CLUB_STATS_POLL_SECONDS = int_with('DUO_CRON_CLUB_STATS_POLL_SECONDS', 300)
CLUB_STATS_BATCH_SIZE = int_with('DUO_CRON_CLUB_STATS_BATCH_SIZE', 200)
CLUB_TOP_ANSWERS_POLL_SECONDS = \
    int_with('DUO_CRON_CLUB_TOP_ANSWERS_POLL_SECONDS', 10 * 60)
CLUB_TOP_ANSWERS_BATCH_SIZE = \
    int_with('DUO_CRON_CLUB_TOP_ANSWERS_BATCH_SIZE', 30)
CLUB_SEO_POLL_SECONDS = int_with('DUO_CRON_CLUB_SEO_POLL_SECONDS', 60)
CLUB_SEO_BATCH_SIZE = int_with('DUO_CRON_CLUB_SEO_BATCH_SIZE', 20)
CLUB_SEO_CONCURRENCY = int_with('DUO_CRON_CLUB_SEO_CONCURRENCY', 10)
CLUB_SEO_MAX_AGE_DAYS = int_with('DUO_CRON_CLUB_SEO_MAX_AGE_DAYS', 30)
CLUB_SEO_MODEL = str_with('DUO_CRON_CLUB_SEO_MODEL', 'gpt-4o-mini')
CLUB_OVERLAP_POLL_SECONDS = \
    int_with('DUO_CRON_CLUB_OVERLAP_POLL_SECONDS', 6 * 60 * 60)
CLUB_COUNT_POLL_SECONDS = int_with('DUO_CRON_CLUB_COUNT_POLL_SECONDS', 1)
CLUB_EMBEDDINGS_POLL_SECONDS = \
    int_with('DUO_CRON_CLUB_EMBEDDINGS_POLL_SECONDS', 60 * 60)
CLUB_EMBEDDINGS_COMPUTE_TIMEOUT_SECONDS = \
    int_with('DUO_CRON_CLUB_EMBEDDINGS_COMPUTE_TIMEOUT_SECONDS', 600)
CLUB_EMBEDDINGS_WRITE_BATCH_SIZE = \
    int_with('DUO_CRON_CLUB_EMBEDDINGS_WRITE_BATCH_SIZE', 50)
# When set, skip the OpenAI call and use this string. Lets the tests
# exercise the cron without an API key.
CLUB_SEO_MOCK_DESCRIPTION = str_or_none('DUO_CRON_CLUB_SEO_MOCK_DESCRIPTION')
