name: Flake Stress

on:
  push:
    branches:
      - flaky-ci-tests

defaults:
  run:
    working-directory: backend

jobs:
  stress:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Stress one test
        run: |
          ./test/util/with-container.sh \
            ./test/util/stress.sh ./functionality6/xmpp-rate-limit.sh 6
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

          DUO_CRON_PHOTO_CLEANER_DRY_RUN: 'true'
          DUO_CRON_AUDIO_CLEANER_DRY_RUN: 'true'
